version: '3.8'

services:
  luprinchef:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: luprinchef_app
    ports:
      - "3002:3000"
    volumes:
      # Montamos la carpeta data para que la base de datos (SQLite) 
      # y el caché de Pexels sean persistentes entre reinicios
      - ./data:/app/data
    env_file:
      - .env
    restart: unless-stopped
